# Generated by Django 4.1.2 on 2022-11-20 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='123', max_length=10, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
